### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by peraaxd** [inirey/multi-device#3]
![Screenshot_20220413-162648~2](https://user-images.githubusercontent.com/71998161/163145521-716a8aed-01ef-4f4c-9ab9-ca1339c54685.png)

Ini kenapa ya bang.. pas saya run malah gini

**Comment by peraaxd** [comment]
> ![Screenshot_20220413-162648~2](https://user-images.githubusercontent.com/71998161/163145521-716a8aed-01ef-4f4c-9ab9-ca1339c54685.png)
> 
> Ini kenapa ya bang.. pas saya run malah gini

Padahal udh saya npm install sama npm update..

**Comment by inirey** [comment]
> > ![Screenshot_20220413-162648~2](https://user-images.githubusercontent.com/71998161/163145521-716a8aed-01ef-4f4c-9ab9-ca1339c54685.png)
> > Ini kenapa ya bang.. pas saya run malah gini
> 
> Padahal udh saya npm install sama npm update..

Coba ulang ad yg kurang tadi xixixi

**Comment by peraaxd** [comment]
> > > ![Screenshot_20220413-162648~2](https://user-images.githubusercontent.com/71998161/163145521-716a8aed-01ef-4f4c-9ab9-ca1339c54685.png)
> > > Ini kenapa ya bang.. pas saya run malah gini
> > 
> > 
> > Padahal udh saya npm install sama npm update..
> 
> Coba ulang ad yg kurang tadi xixixi

Okoklh thanks bang udh bisa
